In [45]:
#applying LDA
import numpy as np

In [46]:
X_train = np.load("drive/MyDrive/X_train.npy", allow_pickle= True)
X_test = np.load("drive/MyDrive/X_test.npy", allow_pickle= True)
X_val = np.load("drive/MyDrive/X_val.npy", allow_pickle= True)

In [47]:
from keras.datasets import mnist
import numpy as np
from sklearn.model_selection import train_test_split

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x = np.concatenate((x_train, x_test))
y = np.concatenate((y_train, y_test))

train_size = 0.7
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=train_size)

In [49]:
nx_train = []

for i in range(len(x_train)):
  nx_train.append(x_train[i].flatten())

nx_test = []

for i in range(len(x_test)):
  nx_test.append(x_test[i].flatten())


In [58]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(nx_train)
x_test = sc.transform(nx_test)

In [59]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=9)
clf = lda.fit(x_train, y_train)
x_train = clf.transform(x_train)
x_test = clf.transform(x_test)

In [60]:
import keras as K
model = K.models.Sequential()
model.add(K.layers.Dense(units=30, input_dim=9,
  activation='relu'))
model.add(K.layers.Dense(units=100,
  activation='relu'))
model.add(K.layers.Dense(units=50,
  activation='relu'))
model.add(K.layers.Dense(units=1,
  activation='softmax'))
model.compile(loss='categorical_crossentropy',
  optimizer='adam', metrics=['accuracy'])

In [61]:
num_epochs = 10
h = model.fit(x_train, y_train, batch_size=50,
  epochs=num_epochs, verbose= 0) 

In [62]:
eval = model.evaluate(x_test, y_test, verbose=0)
print("\nEvaluation on test data: \nloss = %0.4f \
    accuracy = %0.2f%%" % (eval[0], eval[1]*100) )

print("\nEnd MNIST DNN demo \n")


Evaluation on test data: 
loss = 0.0000     accuracy = 11.21%

End MNIST DNN demo 



[[1914    4    8   10    8   37   29    1   32    5]
 [   0 2204   15   11    5   13    2    4   51    3]
 [  28   61 1692   76   51    7   79   19  111   16]
 [   7   27   54 1824    5   88    7   34   52   46]
 [   1   20    8    1 1853    9   14    2   26  153]
 [  24   23    9   82   25 1505   41   13   73   36]
 [  23   17   22    0   46   48 1876    0   26    1]
 [  11   51   16   18   60    7    0 1888    8  169]
 [   9   98   24   70   23   92   16    6 1662   56]
 [  16    6    5   31  110    9    0  121   24 1777]]
Accuracy0.8664285714285714
